### ISSUE TITLE
New students

### ISSUE THREAD

**Issue by mjslee** [fredhohman/brad-myers-advisee-tree#2]
Hello! I know there hasn't been updates in a while, but I was hoping you could add my two new students to the tree:

9.9.3	Ruiqi (Rachel) Shen	Michael J. Lee
9.9.4	Tianchi (Maverick) Mo	Michael J. Lee

**Comment by fredhohman** [comment]
Hi there.

Absolutely! I'll add them later today. 

Also, note that there is a [google doc](https://docs.google.com/document/d/1NKheBhylXdkY_lmcV1QEP7CCLiwpMjE2L-KnWWh0Nvo/edit#heading=h.h4g51lbmhlnj) with the full info there too. Any edits to that doc are sent to Brad and *should* also notify me too to add them to the visualization.

**Comment by mjslee** [comment]
Excellent, I wasn't sure if the googledoc was still being tracked. I'll add the info there also to be redundant. Thanks!

**Comment by fredhohman** [comment]
@mjslee I've added your new students in commit d2794c7fde35e715d9b8083b6990c9c63430e55e! 

They are now included in the visualization.

Thanks!

**Comment by mjslee** [comment]
Hi Fred! Re-opening this issue instead of making a new one. Can you kindly update entry 9.9.4 with the updated name above when you have the chance? Thank you!

**Comment by fredhohman** [comment]
You bet! Updated in 8e63115657c51368163d14be4b791c24f2a1050e.
