### ISSUE TITLE
A glitch in the tree

### ISSUE THREAD

**Issue by ZainabIftikhar** [fredhohman/brad-myers-advisee-tree#6]
Cool animation! Just wanted to let you that this part of the tree is wrongly associated. 

Brandon Woodard, Ji Won Chung, Zainab Iftikhar, Tongyu Zhou and Talie Massachi are students of Jeff, not Shaun! 

<img width="1169" alt="Screen Shot 2023-05-08 at 6 56 30 PM" src="https://user-images.githubusercontent.com/23429685/236954885-624d1d15-c070-4510-ac53-e6e8f56fafc5.png">

probably a small fix in the data.csv

**Comment by ZainabIftikhar** [comment]
I have rectified this, and can open a pull request if you can temporarily give me write access!

**Comment by fredhohman** [comment]
Whoops, must have been a typo! Thanks for catching this @ZainabIftikhar! 

Wait, are you not able to submit a PR right now?

**Comment by ZainabIftikhar** [comment]
I was trying to submit one without needing to fork!
